# Generated by Django 2.2.27 on 2022-05-23 02:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propietario', models.CharField(max_length=50)),
                ('apellido_propietario', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universidades_cercanas', multiselectfield.db.fields.MultiSelectField(choices=[('Universidad del Bio Bio', 'Universidad del Bio Bio'), ('Universidad De La Santisima Concepcion', 'Universidad De La Santisima Concepcion'), ('Universidad San Sebastián', 'Universidad San Sebastián'), ('Advance Universidad San Sebastián', 'Advance Universidad San Sebastián'), ('Universidad Diego Portales', 'Universidad Diego Portales'), ('Universidad del Desarrollo', 'Universidad del Desarrollo'), ('Universidad del Pacífico', 'Universidad del Pacífico'), ('Universidad Técnica Federico Santa María', 'Universidad Técnica Federico Santa María'), ('INACAP - Universidad Tecnológica de Chile', 'INACAP - Universidad Tecnológica de Chile'), ('INACAP - Universidad Andrés Bello', 'INACAP - Universidad Andrés Bello'), ('Universidad Andrés Bello Postgrados', 'Universidad Andrés Bello Postgrados'), ('Universidad Arcis - Concepción', 'Universidad Arcis - Concepción'), ('Universidad Santo Tomás', 'Universidad Santo Tomás'), ('DUOC UC', 'DUOC UC'), ('Instituto Profesional DUOC UC', 'Instituto Profesional DUOC UC'), ('Universidad del Desarrollo', 'Universidad del Desarrollo'), ('Educacion Ejecutiva - Facultad de Economía y Negocios - UDD (Universidad del Desarrollo)', 'Educacion Ejecutiva - Facultad de Economía y Negocios - UDD (Universidad del Desarrollo)'), ('Universidad de Concepcion', 'Universidad de Concepcion')], default=None, max_length=589)),
                ('sector_propiedad', models.CharField(max_length=50)),
                ('direccion', models.CharField(default=None, max_length=80)),
                ('precio_arriendo', models.IntegerField()),
                ('tipo_propiedad', models.CharField(choices=[('departamento', 'departamento'), ('casa', 'casa')], default=None, max_length=20)),
                ('cantidad_banos', models.IntegerField(default=None)),
                ('cantidad_habitaciones', models.IntegerField(default=None)),
                ('amoblado', models.BooleanField(default=None)),
                ('superficie_total', models.IntegerField(default=None)),
                ('estacionamiento', models.BooleanField(default=None)),
                ('gastos_comunes', models.IntegerField(default=None)),
                ('servicio_aseo', models.BooleanField(default=None)),
                ('propietario', models.ManyToManyField(to='unidepApp.Propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_estudiante', models.CharField(max_length=9)),
                ('nombre_estudiante', models.CharField(max_length=50)),
                ('apellido_estudiante', models.CharField(max_length=50)),
                ('universidad', models.CharField(choices=[('Universidad del Bio Bio', 'Universidad del Bio Bio'), ('Universidad De La Santisima Concepcion', 'Universidad De La Santisima Concepcion'), ('Universidad San Sebastián', 'Universidad San Sebastián'), ('Advance Universidad San Sebastián', 'Advance Universidad San Sebastián'), ('Universidad Diego Portales', 'Universidad Diego Portales'), ('Universidad del Desarrollo', 'Universidad del Desarrollo'), ('Universidad del Pacífico', 'Universidad del Pacífico'), ('Universidad Técnica Federico Santa María', 'Universidad Técnica Federico Santa María'), ('INACAP - Universidad Tecnológica de Chile', 'INACAP - Universidad Tecnológica de Chile'), ('INACAP - Universidad Andrés Bello', 'INACAP - Universidad Andrés Bello'), ('Universidad Andrés Bello Postgrados', 'Universidad Andrés Bello Postgrados'), ('Universidad Arcis - Concepción', 'Universidad Arcis - Concepción'), ('Universidad Santo Tomás', 'Universidad Santo Tomás'), ('DUOC UC', 'DUOC UC'), ('Instituto Profesional DUOC UC', 'Instituto Profesional DUOC UC'), ('Universidad del Desarrollo', 'Universidad del Desarrollo'), ('Educacion Ejecutiva - Facultad de Economía y Negocios - UDD (Universidad del Desarrollo)', 'Educacion Ejecutiva - Facultad de Economía y Negocios - UDD (Universidad del Desarrollo)'), ('Universidad de Concepcion', 'Universidad de Concepcion')], default=None, max_length=100)),
                ('presupuesto', models.IntegerField()),
                ('propiedad', models.ManyToManyField(to='unidepApp.Propiedad')),
            ],
        ),
    ]
