# Generated by Django 2.2.27 on 2022-05-24 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidepApp', '0003_auto_20220524_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='precio_arriendo',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Solo están permitidos carácteres alfanuméricos.')]),
        ),
    ]
