# Generated by Django 2.2.27 on 2022-05-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidepApp', '0004_auto_20220524_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos_propiedad'),
        ),
    ]
